bump spat to 0.1.0a5+git20250512.fccb581

diff --git a/debbuild/spat/Makefile b/debbuild/spat/Makefile
--- a/debbuild/spat/Makefile
+++ b/debbuild/spat/Makefile
@@ -1,29 +1,43 @@
 all: setup build move
 
-TARBALL := spat-0.1.0a4.tar.gz
+TARBALL := spat-0.1.0a5+git20250512.fccb581.tar.gz
+SOURCE_TARBALL ?= ../SOURCES/$(TARBALL)
+BUILD_DIR := build
+PKG_OUTPUT_DIR ?= $(HOME)/ext/pkg
+PATCHES := $(sort $(wildcard patches/*.patch))
+
+check-src:
+	@test -f "$(SOURCE_TARBALL)" || (echo "missing $(SOURCE_TARBALL), run pig build get first; if needed, copy $(TARBALL) into ../SOURCES"; exit 1)
 
 # prepare directory
-setup:
-	rm -rf build; mkdir -p build
-	tar -C build --strip-components=1 -xf ../SOURCES/$(TARBALL)
+setup: check-src
+	rm -rf $(BUILD_DIR); mkdir -p $(BUILD_DIR)
+	tar -C $(BUILD_DIR) --strip-components=1 -xf "$(SOURCE_TARBALL)"
+	find $(BUILD_DIR) \( -name '._*' -o -name '.DS_Store' \) -delete
+	@$(MAKE) apply-patches
 	pg_buildext updatecontrol
-	rm -rf build/debian; cp -r debian build/debian
+	rm -rf $(BUILD_DIR)/debian; cp -r debian $(BUILD_DIR)/debian
 	OS_CODENAME=$(shell lsb_release -sc); \
-	sed -i "1s/PGSTY)/PGSTY~$${OS_CODENAME})/" build/debian/changelog
+	sed -i "1s/PGSTY)/PGSTY~$${OS_CODENAME})/" $(BUILD_DIR)/debian/changelog
+
+apply-patches:
+	@set -e; \
+	for p in $(PATCHES); do \
+		echo "apply $$p"; \
+		(cd $(BUILD_DIR) && patch -p1 < "../$$p"); \
+	done
 
 # building deb
 build:
-	cd build && pg_buildext updatecontrol
-	cd build && dpkg-buildpackage -b -us -uc
+	cd $(BUILD_DIR) && pg_buildext updatecontrol
+	cd $(BUILD_DIR) && dpkg-buildpackage -b -us -uc
 
 # collect deb
 move:
-	mkdir -p ~/ext/pkg && cp *.deb ~/ext/pkg/
+	mkdir -p $(PKG_OUTPUT_DIR) && cp *.deb $(PKG_OUTPUT_DIR)/
 
 # remove building craps
 clean:
-	rm -rf *.buildinfo *.changes *.ddeb *.deb
+	rm -rf $(BUILD_DIR) *.buildinfo *.changes *.ddeb *.deb
 
-.PHONY: all setup update build move clean ls
-
-
+.PHONY: all check-src setup apply-patches update build move clean ls
