bump pg_cardano from 1.1.1 to 1.2.0

diff --git a/debbuild/pg_cardano/Makefile b/debbuild/pg_cardano/Makefile
--- a/debbuild/pg_cardano/Makefile
+++ b/debbuild/pg_cardano/Makefile
@@ -1,35 +1,61 @@
 all: setup build move
 
-TARBALL := pg_cardano-1.1.1.tar.gz
+TARBALL := pg_cardano-1.2.0.tar.gz
+SOURCE_TARBALL ?= $(firstword $(wildcard $(HOME)/ext/src/$(TARBALL) $(HOME)/pgsty/repo/ext/src/$(TARBALL) ../SOURCES/$(TARBALL) ../../src/$(TARBALL)))
+BUILD_DIR := build
+PKG_OUTPUT_DIR ?= $(HOME)/ext/pkg
+PG_VERSIONS := 15 16 17 18
+PGRX_VERSION := 0.17.0
+PGRX_PATCH := patches/pgrx-0.17.0-pbox-nonnull.patch
 
-# prepare directory
-setup:
-	rm -rf build; mkdir -p build
-	tar -C build --strip-components=1 -xf ../SOURCES/$(TARBALL)
-	pg_buildext updatecontrol
-	rm -rf build/debian; cp -r debian build/debian
-	OS_CODENAME=$(shell lsb_release -sc); \
-	sed -i "1s/PIGSTY)/PIGSTY~$${OS_CODENAME})/" build/debian/changelog
+check-src:
+	@test -n "$(SOURCE_TARBALL)" || (echo "missing $(TARBALL), run: pig build get pg_cardano; if unavailable, place the source archive under $(HOME)/pgsty/repo/ext/src or ../SOURCES"; exit 1)
+
+setup: check-src
+	rm -rf $(BUILD_DIR); mkdir -p $(BUILD_DIR)
+	tar -C $(BUILD_DIR) --strip-components=1 -xf "$(SOURCE_TARBALL)"
+	find $(BUILD_DIR) -name '._*' -delete
+	rm -rf $(BUILD_DIR)/debian; cp -r debian $(BUILD_DIR)/debian
+	OS_CODENAME=$$( (lsb_release -sc 2>/dev/null) || (. /etc/os-release 2>/dev/null; echo $${VERSION_CODENAME:-$${UBUNTU_CODENAME:-unknown}}) ); \
+	sed -i "1s/PIGSTY)/PIGSTY~$${OS_CODENAME})/" $(BUILD_DIR)/debian/changelog
 
 build: building packaging
-building:
-	cd build && cargo update && \
-	for PG_VERSION in 14 15 16 17 18; do \
-	    PATH=/usr/lib/postgresql/$$PG_VERSION/bin:~/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
-	    PG_CONFIG=/usr/lib/postgresql/$$PG_VERSION/bin/pg_config \
-	    cargo pgrx package -v; \
+
+building: ensure-pgrx
+	cd $(BUILD_DIR) && \
+	PATH="$$HOME/.cargo/bin:$$PATH" cargo pgrx init \
+	    --pg15=/usr/lib/postgresql/15/bin/pg_config \
+	    --pg16=/usr/lib/postgresql/16/bin/pg_config \
+	    --pg17=/usr/lib/postgresql/17/bin/pg_config \
+	    --pg18=/usr/lib/postgresql/18/bin/pg_config \
+	    --no-run
+	cd $(BUILD_DIR) && PATH="$$HOME/.cargo/bin:$$PATH" cargo fetch
+	@PBOX="$$(find "$$HOME/.cargo/registry/src" -path '*/pgrx-$(PGRX_VERSION)/src/palloc/pbox.rs' | head -n 1)"; \
+	test -n "$$PBOX"; \
+	if ! grep -q 'NonNull::from(\&mut datum)' "$$PBOX"; then \
+	    (cd "$$(dirname "$$PBOX")" && patch -p0 < "$(CURDIR)/$(PGRX_PATCH)"); \
+	fi
+	cd $(BUILD_DIR) && \
+	for PG_VERSION in $(PG_VERSIONS); do \
+	    PATH=/usr/lib/postgresql/$$PG_VERSION/bin:$$HOME/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
+	    cargo pgrx package -v --no-default-features --features pg$$PG_VERSION --pg-config /usr/lib/postgresql/$$PG_VERSION/bin/pg_config; \
 	done
 
+ensure-pgrx:
+	@CURRENT=$$(cargo pgrx --version 2>/dev/null | awk '{print $$2}'); \
+	if [ "$$CURRENT" != "$(PGRX_VERSION)" ]; then \
+	    cargo install --locked cargo-pgrx --version $(PGRX_VERSION); \
+	fi
+
 packaging:
-	cd build && pg_buildext updatecontrol
-	cd build && dpkg-buildpackage -b -us -uc
+	cd $(BUILD_DIR) && pg_buildext updatecontrol
+	# Builder images provide Rust/Clang toolchains outside dpkg, so skip strict Build-Depends checks here.
+	cd $(BUILD_DIR) && dpkg-buildpackage -b -us -uc -d
 
-# collect deb
 move:
-	mkdir -p ~/ext/pkg && cp *.deb ~/ext/pkg/
+	mkdir -p $(PKG_OUTPUT_DIR) && cp *.deb $(PKG_OUTPUT_DIR)/
 
-# remove building craps
 clean:
-	rm -rf *.buildinfo *.changes *.ddeb *.deb
+	rm -rf $(BUILD_DIR) *.buildinfo *.changes *.ddeb *.deb
 
-.PHONY: all setup update build building packaging move clean ls
+.PHONY: all check-src setup build building ensure-pgrx packaging move clean
