bump pg_search to 0.25.6

diff --git a/debbuild/pg_search/Makefile b/debbuild/pg_search/Makefile
--- a/debbuild/pg_search/Makefile
+++ b/debbuild/pg_search/Makefile
@@ -1,12 +1,14 @@
 all: setup build move
 
-TARBALL := pg_search-0.25.2.tar.gz
+TARBALL := pg_search-0.25.6.tar.gz
 SOURCE_TARBALL ?= ../SOURCES/$(TARBALL)
 BUILD_DIR := build
 PKG_OUTPUT_DIR ?= $(HOME)/ext/pkg
 PG_VERSIONS := 15 16 17 18
-PGRX_VERSION := 0.19.1
-SOURCE_PATCH := patches/pg-search-0.25.2.patch
+PGRX_VERSION := 0.19.2
+RUST_TOOLCHAIN := 1.97.1
+SOURCE_PATCH := patches/pg-search-0.25.6.patch
+LICENSE_COLLECTOR := collect-third-party-licenses.py
 CARGO_NET_GIT_FETCH_WITH_CLI ?= true
 CARGO_BUILD_JOBS ?= 2
 
@@ -16,6 +18,7 @@ check-src:
 # prepare directory
 check-patches:
 	@test -f "$(SOURCE_PATCH)" || (echo "missing $(SOURCE_PATCH), keep the source patch name aligned with $(TARBALL)"; exit 1)
+	@test -f "$(LICENSE_COLLECTOR)" || (echo "missing $(LICENSE_COLLECTOR)" >&2; exit 1)
 
 setup: check-src check-patches
 	rm -rf $(BUILD_DIR); mkdir -p $(BUILD_DIR)
@@ -24,40 +27,49 @@ setup: check-src check-patches
 	rm -rf $(BUILD_DIR)/debian; cp -r debian $(BUILD_DIR)/debian
 	printf '%s\n' $(PG_VERSIONS) > $(BUILD_DIR)/debian/pgversions
 	@$(MAKE) apply-patches
-	OS_CODENAME=$$( (lsb_release -sc 2>/dev/null) || (. /etc/os-release 2>/dev/null; echo $${VERSION_CODENAME:-$${UBUNTU_CODENAME:-unknown}}) ); \
+	OS_CODENAME=$$(lsb_release -sc 2>/dev/null || (. /etc/os-release 2>/dev/null; echo $${VERSION_CODENAME:-$${UBUNTU_CODENAME:-unknown}}) || echo unknown); \
+	test -n "$$OS_CODENAME" || OS_CODENAME=unknown; \
 	perl -0pi -e "s/PGSTY\\)/PGSTY~$${OS_CODENAME})/" $(BUILD_DIR)/debian/changelog
 
 apply-patches:
 	@echo "apply $(SOURCE_PATCH)"
-	@(cd $(BUILD_DIR) && patch -p1 --forward -f < "../$(SOURCE_PATCH)")
+	@(cd $(BUILD_DIR) && patch --fuzz=0 --batch --forward -p1 < "../$(SOURCE_PATCH)")
 
 build: building packaging
 
 building: check-pgrx
 	cd $(BUILD_DIR) && \
-	PATH="$$HOME/.cargo/bin:$$PATH" cargo pgrx init \
+	RUSTUP_TOOLCHAIN=$(RUST_TOOLCHAIN) PATH="$$HOME/.cargo/bin:$$PATH" cargo pgrx init \
 	    --pg15=/usr/lib/postgresql/15/bin/pg_config \
 	    --pg16=/usr/lib/postgresql/16/bin/pg_config \
 	    --pg17=/usr/lib/postgresql/17/bin/pg_config \
 	    --pg18=/usr/lib/postgresql/18/bin/pg_config \
 	    --no-run
-	cd $(BUILD_DIR) && find . -path '*/target' -prune -o -name Cargo.lock -type f -print0 | sort -z | xargs -0 -r sha256sum > .pgrx0191-cargo-locks.before
-	@test -s $(BUILD_DIR)/.pgrx0191-cargo-locks.before
-	cd $(BUILD_DIR) && PATH="$$HOME/.cargo/bin:$$PATH" CARGO_NET_GIT_FETCH_WITH_CLI=$(CARGO_NET_GIT_FETCH_WITH_CLI) cargo fetch --locked
+	cd $(BUILD_DIR) && find . -path '*/target' -prune -o -name Cargo.lock -type f -print0 | sort -z | xargs -0 -r sha256sum > .pgrx0192-cargo-locks.before
+	@test -s $(BUILD_DIR)/.pgrx0192-cargo-locks.before
+	cd $(BUILD_DIR) && RUSTUP_TOOLCHAIN=$(RUST_TOOLCHAIN) PATH="$$HOME/.cargo/bin:$$PATH" CARGO_NET_GIT_FETCH_WITH_CLI=$(CARGO_NET_GIT_FETCH_WITH_CLI) cargo fetch --locked
 	cd $(BUILD_DIR)/pg_search && \
-	export RUSTUP_TOOLCHAIN=stable; \
+	export RUSTUP_TOOLCHAIN=$(RUST_TOOLCHAIN); \
 	export CARGO_BUILD_JOBS="$(CARGO_BUILD_JOBS)"; \
 	export RUSTFLAGS="$${RUSTFLAGS:-} -C link-arg=-Wl,--no-gc-sections"; \
 	for PG_VERSION in $(PG_VERSIONS); do \
-	    PATH=/usr/lib/postgresql/$$PG_VERSION/bin:$$HOME/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
-	    PG_CONFIG=/usr/lib/postgresql/$$PG_VERSION/bin/pg_config \
-	    CARGO_NET_OFFLINE=true CARGO_NET_GIT_FETCH_WITH_CLI=$(CARGO_NET_GIT_FETCH_WITH_CLI) cargo pgrx package -v --no-default-features --features pg$$PG_VERSION --pg-config /usr/lib/postgresql/$$PG_VERSION/bin/pg_config; \
-	done
-	cd $(BUILD_DIR) && find . -path '*/target' -prune -o -name Cargo.lock -type f -print0 | sort -z | xargs -0 -r sha256sum > .pgrx0191-cargo-locks.after
-	cmp $(BUILD_DIR)/.pgrx0191-cargo-locks.before $(BUILD_DIR)/.pgrx0191-cargo-locks.after
+		    PATH=/usr/lib/postgresql/$$PG_VERSION/bin:$$HOME/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
+			    PG_CONFIG=/usr/lib/postgresql/$$PG_VERSION/bin/pg_config \
+			    CARGO_NET_OFFLINE=true CARGO_NET_GIT_FETCH_WITH_CLI=$(CARGO_NET_GIT_FETCH_WITH_CLI) cargo pgrx package -v --no-default-features --features pg$$PG_VERSION --pg-config /usr/lib/postgresql/$$PG_VERSION/bin/pg_config; \
+		done
+	cd $(BUILD_DIR) && find . -path '*/target' -prune -o -name Cargo.lock -type f -print0 | sort -z | xargs -0 -r sha256sum > .pgrx0192-cargo-locks.after
+	cmp $(BUILD_DIR)/.pgrx0192-cargo-locks.before $(BUILD_DIR)/.pgrx0192-cargo-locks.after
+	cd $(BUILD_DIR) && \
+		TARGET_TRIPLE=$$(RUSTUP_TOOLCHAIN=$(RUST_TOOLCHAIN) rustc -vV | sed -n 's/^host: //p'); \
+		RUSTUP_TOOLCHAIN=$(RUST_TOOLCHAIN) CARGO_NET_OFFLINE=true cargo metadata --locked --offline \
+		  --manifest-path pg_search/Cargo.toml --no-default-features \
+		  --features pg$(firstword $(PG_VERSIONS)) --filter-platform "$$TARGET_TRIPLE" \
+		  --format-version=1 > .cargo-metadata-pg-search.json
+	cd $(BUILD_DIR) && python3 ../$(LICENSE_COLLECTOR) \
+		.cargo-metadata-pg-search.json third-party-licenses
 
 check-pgrx:
-	@CURRENT=$$(cargo pgrx --version 2>/dev/null | awk '{print $$2}'); \
+	@CURRENT=$$(RUSTUP_TOOLCHAIN=$(RUST_TOOLCHAIN) cargo pgrx --version 2>/dev/null | awk '{print $$2}'); \
 	if [ "$$CURRENT" != "$(PGRX_VERSION)" ]; then \
 	    echo "cargo-pgrx $(PGRX_VERSION) is required; run pig build pgrx -v $(PGRX_VERSION) before building" >&2; \
 	    exit 1; \
