bump pg_schedoc to 0.0.2+git20260430.9f135c3

diff --git a/debbuild/pg_schedoc/Makefile b/debbuild/pg_schedoc/Makefile
--- a/debbuild/pg_schedoc/Makefile
+++ b/debbuild/pg_schedoc/Makefile
@@ -1,29 +1,45 @@
 all: setup build move
 
-TARBALL := pg_schedoc-0.0.1.tar.gz
+TARBALL := pg_schedoc-0.0.2+git20260430.9f135c3.tar.gz
+SOURCE_TARBALL ?= ../SOURCES/$(TARBALL)
+SOURCE_COMMIT := 9f135c3427415c61771bbe69dc1cffbb999239f4
+BUILD_DIR := build
+PKG_OUTPUT_DIR ?= $(HOME)/ext/pkg
+PATCHES := $(sort $(wildcard patches/*.patch))
 
-# prepare directory
-setup:
-	rm -rf build; mkdir -p build
-	tar -C build --strip-components=1 -xf ../SOURCES/$(TARBALL)
-	pg_buildext updatecontrol
-	rm -rf build/debian; cp -r debian build/debian
-	OS_CODENAME=$(shell lsb_release -sc); \
-	sed -i "1s/PGSTY)/PGSTY~$${OS_CODENAME})/" build/debian/changelog
+check-src:
+	@test -f "$(SOURCE_TARBALL)" || (echo "missing $(SOURCE_TARBALL), run pig build get first; if needed, copy $(TARBALL) into ../SOURCES"; exit 1)
+
+check-patches:
+	@test "$(words $(PATCHES))" = "1" || (echo "expected exactly one pg_schedoc patch"; exit 1)
+
+setup: check-src check-patches
+	rm -rf $(BUILD_DIR); mkdir -p $(BUILD_DIR)
+	tar -C $(BUILD_DIR) --strip-components=1 -xf "$(SOURCE_TARBALL)"
+	find $(BUILD_DIR) \( -name '._*' -o -name '.DS_Store' \) -delete
+	@$(MAKE) apply-patches
+	rm -rf $(BUILD_DIR)/debian; cp -r debian $(BUILD_DIR)/debian
+	OS_CODENAME=$$( (lsb_release -sc 2>/dev/null) || (. /etc/os-release 2>/dev/null; echo $${VERSION_CODENAME:-$${UBUNTU_CODENAME:-unknown}}) ); \
+	sed -i "1s/PGSTY)/PGSTY~$${OS_CODENAME})/" $(BUILD_DIR)/debian/changelog
+
+apply-patches:
+	@set -e; \
+	for p in $(PATCHES); do \
+		echo "apply $$p"; \
+		(cd $(BUILD_DIR) && patch --fuzz=0 -p1 < "../$$p"); \
+	done
 
 # building deb
 build:
-	cd build && pg_buildext updatecontrol
-	cd build && dpkg-buildpackage -b -us -uc
+	cd $(BUILD_DIR) && pg_buildext updatecontrol
+	cd $(BUILD_DIR) && dpkg-buildpackage -b -us -uc
 
 # collect deb
 move:
-	mkdir -p ~/ext/pkg && cp *.deb ~/ext/pkg/
+	mkdir -p $(PKG_OUTPUT_DIR) && cp *.deb $(PKG_OUTPUT_DIR)/
 
 # remove building craps
 clean:
-	rm -rf *.buildinfo *.changes *.ddeb *.deb
+	rm -rf $(BUILD_DIR) *.buildinfo *.changes *.ddeb *.deb
 
-.PHONY: all setup update build move clean ls
-
-
+.PHONY: all check-src check-patches setup apply-patches build move clean
